### PR TITLE
Github enterprise

### LINKED ISSUE #155: Add support for github enterprise server
Support custom URL for github server to enable use of GitHub enterprise.

### PR DESCRIPTION
**Pull request by stopthatcow**
Support custom github URL to enable use of github enterprise.

Fixes #155

### CODE REVIEW

**Comment by stopthatcow** [comment]
Try this @moorepatrick: you can cult off of the zazu.yaml file in the root of the repo and then add a `url: http://yourgithubserver.com` param to the `codeReviewer` section.

Pull at this branch
Create a virutual env to install into and activate it then `pip install -e .` (note when installed like this zazu will be very slow)

Try `zazu dev review`

**Comment by moorepatrick** [comment]
It's still looking for `https://api.github.com`

```
myrepo.git ❯❯❯ zazu dev review                                                                                                                                                                                                           
No saved GitHub token found in keychain, lets add one...
Username for https://api.github.com:
```

**Comment by stopthatcow** [comment]
Can you attach your zazu.yaml file, run `which zazu` and `zazu --version`?

**Comment by stopthatcow** [comment]
Confirmed WAI offline.

**Pull request merged**
